# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'title.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import urllib.request
from PyQt5 import uic
import webbrowser
import csv
import random
from PyQt5 import QtCore, QtGui, QtWidgets
from test import testClass
from login import WindowClass
form_class = uic.loadUiType("title.ui")[0]

class FirstClass(QMainWindow, form_class):
    def __init__(self) :
        super().__init__()
        self.setupUi(self)
        self.img()
        self.txt()
        self.rebooks=[]
        self.pushButton_3.clicked.connect(self.back)
        self.pushButton_4.clicked.connect(self.login)
        self.pushButton_5.clicked.connect(self.page2)
        self.pushButton_6.clicked.connect(self.page3)
        self.pushButton_7.clicked.connect(self.page1)
        self.pushButton_10.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/scheduleMonth/IG'))
        self.pushButton_8.clicked.connect(self.back)
        self.pushButton_9.clicked.connect(self.back)
        self.pushButton_11.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3370?query='))
        self.pushButton_12.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3367?query='))
        self.pushButton_13.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3361?query='))
        self.pushButton_14.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3360?query='))
        self.pushButton_15.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3358?query='))
        self.pushButton_16.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3336?query='))
        self.pushButton_17.clicked.connect(lambda: webbrowser.open('https://lib.gwangsan.go.kr/main/board/3/1/category13/read/3325?query='))
        self.stackedWidget.setCurrentIndex(0)
        self.reset.clicked.connect(self.resetb)
    def back(self):
        self.stackedWidget.setCurrentIndex(0)
    def page1(self):
        self.stackedWidget.setCurrentIndex(1)
    def page2(self):
        self.stackedWidget.setCurrentIndex(2)
    def page3(self):
        self.stackedWidget.setCurrentIndex(3)
    def img(self):
        # self.label_pic = QLabel(self)
        urlString = 'https://cdn.focus1.kr/news/photo/202102/33994_36352_4713.jpg'
        urlString2= 'https://mblogthumb-phinf.pstatic.net/MjAyMTA4MDNfMjIx/MDAxNjI3OTY1NzIzNjM3.-dzyB2SbQT3Whpq9vn57TCjd-OcdmCryNEDTIh8-fosg.xPOyUmPIn4KIh3yeRTfS0aD1yS9KD7t15FeKXTQTKi4g.JPEG.gwangsan242/SE-3162f674-cded-4200-808f-19adbc76fc09.jpg?type=w800'
        urlString3='https://www.shutterstock.com/image-vector/man-holding-megaphone-speech-bubbles-260nw-2079473878.jpg'
        urlString4='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_1.jpg'
        urlString5 ='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_2.jpg'
        urlString6 ='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_3.jpg'
        urlString7 ='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_4.jpg'
        urlString8 ='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_5.jpg'
        urlString9 ='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_6.jpg'
        urlString10 ='https://lib.gwangsan.go.kr/images/ui/sub/facilitystatus/IG/facilitystatus2_8.jpg'
        imageFromWeb = urllib.request.urlopen(urlString).read()
        imageFromWeb2 = urllib.request.urlopen(urlString2).read()
        imageFromWeb3 = urllib.request.urlopen(urlString3).read()
        imageFromWeb4 = urllib.request.urlopen(urlString4).read()                           #시설이미지
        imageFromWeb5 = urllib.request.urlopen(urlString5).read()
        imageFromWeb6 = urllib.request.urlopen(urlString6).read()
        imageFromWeb7 = urllib.request.urlopen(urlString7).read()
        imageFromWeb8 = urllib.request.urlopen(urlString8).read()
        imageFromWeb9 = urllib.request.urlopen(urlString9).read()
        imageFromWeb10 = urllib.request.urlopen(urlString10).read()

        qPixmapVar = QPixmap()
        qPixmapVar2 = QPixmap()
        qPixmapVar3 = QPixmap()
        qPixmapVar4 = QPixmap()
        qPixmapVar5 = QPixmap()
        qPixmapVar6 = QPixmap()
        qPixmapVar7 = QPixmap()
        qPixmapVar8 = QPixmap()
        qPixmapVar9 = QPixmap()
        qPixmapVar10 = QPixmap()

        qPixmapVar.loadFromData(imageFromWeb)
        qPixmapVar2.loadFromData(imageFromWeb2)
        qPixmapVar3.loadFromData(imageFromWeb3)
        qPixmapVar4.loadFromData(imageFromWeb4)
        qPixmapVar5.loadFromData(imageFromWeb5)
        qPixmapVar6.loadFromData(imageFromWeb6)
        qPixmapVar7.loadFromData(imageFromWeb7)
        qPixmapVar8.loadFromData(imageFromWeb8)
        qPixmapVar9.loadFromData(imageFromWeb9)
        qPixmapVar10.loadFromData(imageFromWeb10)

        self.label_pic.setPixmap(qPixmapVar)
        self.main_pic.setPixmap(qPixmapVar2)
        self.event_pic.setPixmap(qPixmapVar3)
        self.label_11.setPixmap(qPixmapVar4)
        self.label_12.setPixmap(qPixmapVar5)
        self.label_13.setPixmap(qPixmapVar6)
        self.label_14.setPixmap(qPixmapVar7)
        self.label_15.setPixmap(qPixmapVar8)
        self.label_16.setPixmap(qPixmapVar9)
        self.label_17.setPixmap(qPixmapVar10)
    def txt(self):
        self.label_9.setText("일정 및 행사")
        self.label_2.setText("『아이와 부모, 모두가 행복한 생활 속 성인지 감수성』 참여자 모집")
        self.label_3.setText("이야기꽃도서관 빅데이터특강 「데이터 세상을 읽는 새로운 언어, 빅데이터」 수강생 모집")
        self.label_4.setText("이야기꽃도서관 「들썩들썩 옛이야기! 전통문화 한마당」 참여자 모집")
        self.label_5.setText("이야기꽃도서관 연말 특별프로그램 『아듀(Adieu), 2022!!』 참여자 모집")
        self.label_6.setText("이야기꽃도서관 「함께하는 따뜻한 겨울나기」 프로그램 수강생 모집 안내(수정)")
        self.label_7.setText("2022년 이야기꽃도서관 희망도서 마감 안내")
        self.label_8.setText("이야기꽃도서관 북스타트 책꾸러미 2차 배부 안내(마감)")
        self.label.setText("            대지	3,306㎡\n\
            건물면적	3,276㎡(지하1층, 지상3층)\n\
            층별안내	\n\
            [본관]\n\
            3층 – 키우실, 모두의서재실, 느끼실, 작가실, 어울실, 만드실, 사무실\n\
            2층 – 종합자료실(일반,어린이), 디지털자료실, 책읽어주는방\n\
            1층 – 너른마루, 와글와글, 도란도란, 게시판\n\
            지하1층 – 전기실, 기계실, 물탱크실\n\
            [학습관]\n\
            2, 3층 : 학습실, 휴게실, 사무실\n\
            1층 : 로비, 창고")
    def recommend(self):
        f = open('flower.csv', 'r')
        rdr = csv.reader(f)
        num = random.randrange(1, 51456)
        for line in rdr:
            if line[0] == str(num):
                return line
    def resetb(self):
        self.reco.clear()
        for i in range(0,10):
            self.rebooks=(self.recommend())
            print(self.rebooks[4:7])
            self.reco.insertItem(i,str(self.rebooks[4:7]))
    def login(self):
        print("!!!!!!!!")
        widget.setCurrentIndex(1)
if __name__ == "__main__" :
    # form_class = uic.loadUiType("title.ui")[0]
    #QApplication : 프로그램을 실행시켜주는 클래스
    app = QApplication(sys.argv)
    widget = QtWidgets.QStackedWidget()
    #WindowClass의 인스턴스 생성
    myWindow = FirstClass()
    testlogin = testClass()
    # myWindow.img()
    #프로그램 화면을 보여주는 코드
    widget.addWidget(myWindow)
    widget.addWidget(testlogin)
    widget.setFixedHeight(800)
    widget.setFixedWidth(1200)
    widget.show()
    # myWindow.show()
    #프로그램을 이벤트루프로 진입시키는(프로그램을 작동시키는) 코드
    app.exec_()


